# Generated by Django 5.0.6 on 2024-06-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subscript', models.CharField(choices=[('Select a type', 'Select a type'), ('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=13)),
                ('no_of_days', models.IntegerField()),
                ('amount', models.CharField(max_length=200)),
                ('registration_date', models.DateField()),
                ('renewal_date', models.DateField()),
            ],
        ),
    ]
