# Generated by Django 5.0.6 on 2024-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
