# Generated by Django 5.0.6 on 2024-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_hospital_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_renew',
            field=models.BooleanField(default=False),
        ),
    ]
