# Generated by Django 5.0.6 on 2024-06-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hospital_is_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
