# Generated by Django 5.0.6 on 2024-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hospital_amount_alter_hospital_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='amount',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='no_of_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
