# Generated by Django 5.0.6 on 2024-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_hospital_amount_alter_hospital_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='subscript',
            field=models.CharField(choices=[('Select a type', 'Select a type'), ('Permanent', 'Permanent'), ('Temporary', 'Temporary')], default='Select a type', max_length=13),
        ),
    ]
