# Generated by Django 5.0.6 on 2024-06-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hospital_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
