# Generated by Django 5.0.6 on 2024-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_hospital_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_renewal_date_explicitly_set',
            field=models.BooleanField(default=False),
        ),
    ]
