# Generated by Django 5.0.6 on 2024-07-02 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_hospital_is_renewal_date_explicitly_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
